
# Project
site_name: TrustSource ts-scan
site_url: https://trustsource.github.io/ts-scan
site_description: >-
  Provides a static site that introduces the TrustSource guide to operating ts-scan
site_author: TrustSource Team 
# Repository
repo_url: https://github.com/trustsource/ts-scan
edit_uri: ""    # prevents the edit button to link into URL

# Copyright
copyright: Copyright &copy; 2024 <a href="https://www.eacg.de/editorial">EACG GmbH</a>

nav:
  - Overview: 
    - 'index.md'
    - Adding Features: 'adding.md'
    - Coding Guidelines: 'guidelines.md'
  - Installation: 'setup.md'
  - Usage: 
    - 'usage.md'
    - Scan for:
      - dependencies: 'sbom.md'
      - licenses: 'licenses.md'
      - encryption: 'encryption.md'
      - vulnerabilities: 'vulns.md'
      - malware: 'malware.md'
      - snippets: 'snippets.md'
    - Convert: 
      - 'convert.md'
    - Operate:
      - multiple artefacts: 'multiscan.md'
      - exporting results: 'exports.md'
      - operating inside a container: 'conatiner.md'
    - Use Cases:
      - Auto Scan on Commit: 'uc01-autoSoCommit.md'
      - Add SBOM 2 Git: 'uc02-SBOM2Git.md'
      - Check 4 Vulns before commit: 'uc03-eval.md'
  - Security: 'security.md'
  - About: 
    - 'about.md'
    - Changelog: 'CHANGELOG.md'


theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: white
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
  font: false # set false, to comply with data privacy (google fonts)
  #  text: Open Sans
  #  code: Courier
  logo: assets/TS_logo_lang.png
  favicon: assets/favicon.png
  icon:
    repo: fontawesome/brands/github
  features:
    # - navigation.expand 
    # - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - header.autohide
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate

extra:
  homepage: https://www.trustsource.io
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well as to measure the effectiveness of our documentation and whether users find what they're searching for. With your consent, you're helping us to make our documentation better. 
    cookies:
      analytics: 
        name: Google Analytics
        checked: false
    actions:
      - accept
      - manage
      - reject
  #version:
  #  provider: mike
  #  default: stable
  analytics:
    provider: google
    property: G-ZSZXY48Y3G
  feedback:
    title: Was this page helpful?
    ratings:
      - icon: material/emoticon-happy-outline
        name: This page was helpful
        data: 1
        note: >-
         Thanks for your feedback!
      - icon: material/emoticon-sad-outline
        name: This page could be improved
        data: 0
        note: >-
         Thanks for your feedback! Help us improve this page by
         using our <a href="https://www.trustsource.io/contact" target="_blank" rel="noopener">feedback form</a>.
  social:
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/trustsource
      name: TrustSource @ Linkedin
    - icon: fontawesome/solid/paper-plane
      link: mailto:support@trustsource.io

extra_javascript:
  - assets/feedback.js
