permissions:
  contents: read

name: Build and Push Docker Image
on:
  push:
    tags:
      - '*'  # Trigger only when a new tag is pushed
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.FRED4TS2DH }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            trustsource/ts-deepscan:latest
            trustsource/ts-deepscan:${{ github.ref_name }}
